## Coursera Developing Data Products Course Project

### Synopsis

These are the files produced during a homework assignment of Coursera's MOOC Developing Data Products from Johns Hopkins University, where students could pick any dataset, and should produce a web app hosted on SaaS platform from RStudio shinyapss.io.

For simplicity, we chose `mtcars` dataset

The materials can be found in:

Web app: https://amardeep.shinyapps.io/mtcarsshinyapp

GitHub Repo: https://github.com/amardeepkrgupta/datasciencecoursera/developing_data_products

## Code for plots

ggplot 2 Library was used for the plotting. Here is the code for a static view of the default plot that is rendered on the web app:
```{r}
library(ggplot2)
trainData <- read.csv("mtcars.csv", header = T)
g <- ggplot(trainData, aes(cyl, mpg))
g + geom_point(aes(color=cyl)) + facet_grid(am ~.)
```

 

## Guidelines to reproduce locally

Guidelines to reproduce this project locally on your PC

To run locally this App on your computer you do NOT need to fork this repo. Please follow these instructions:

1. Install the necessary packages to run RStudio's Shiny Server locally. Please view the well documented requirements in the getting started page: http://shiny.rstudio.com/articles/shinyapps.html

2. Run the following command in the RStudio:

 runGitHub( "datasciencecoursera/developing_data_products", "amardeepkrgupta")

